// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using devitemapi.Entity;

namespace devitemapi.Migrations
{
    [DbContext(typeof(DevDbContext))]
    [Migration("20201030020736_2020-10-30")]
    partial class _20201030
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("devitemapi.Entity.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("devitemapi.Entity.DevAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ActionName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUser")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifyUser")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("DevActions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b48a7f0-4077-4c1e-acd5-87ef0a8ace93"),
                            ActionCode = "Query",
                            ActionName = "查询",
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(5951),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(5955)
                        },
                        new
                        {
                            Id = new Guid("532e849c-b3d5-4d55-abfe-6e645ba2bae2"),
                            ActionCode = "Add",
                            ActionName = "增加",
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(6878),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(6882)
                        },
                        new
                        {
                            Id = new Guid("39579c2f-7f92-4cd0-bf51-76a7a01c8e16"),
                            ActionCode = "Delete",
                            ActionName = "删除",
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(6908),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(6909)
                        },
                        new
                        {
                            Id = new Guid("255f3693-099d-432a-9a80-e377976f9c22"),
                            ActionCode = "View",
                            ActionName = "查看",
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(6913),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(6914)
                        });
                });

            modelBuilder.Entity("devitemapi.Entity.DevMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUser")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MenuCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MenuName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifyUser")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Path")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("DevMenus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("19b93b25-5230-425b-b5c5-625b708915b5"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(2757),
                            Icon = "/item.ico",
                            MenuCode = "Index",
                            MenuName = "首页",
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(2762),
                            ParentId = new Guid("edc8f6c4-d734-49cf-9250-759d966e8641"),
                            Path = "index"
                        },
                        new
                        {
                            Id = new Guid("daf50ad9-c46b-43de-aab2-ca4418785ba3"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(5110),
                            Icon = "/item.ico",
                            MenuCode = "About",
                            MenuName = "关于",
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(5114),
                            ParentId = new Guid("edc8f6c4-d734-49cf-9250-759d966e8641"),
                            Path = "about"
                        },
                        new
                        {
                            Id = new Guid("a5e189c0-166a-4b37-93ee-45ecf1ff11c5"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(5177),
                            Icon = "/item.ico",
                            MenuCode = "System",
                            MenuName = "系统设置",
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(5178),
                            ParentId = new Guid("edc8f6c4-d734-49cf-9250-759d966e8641"),
                            Path = "system"
                        },
                        new
                        {
                            Id = new Guid("1ce75274-4033-4081-88d0-6ba7ef00fddd"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(5184),
                            Icon = "/item.ico",
                            MenuCode = "People",
                            MenuName = "人员管理",
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(5185),
                            ParentId = new Guid("a5e189c0-166a-4b37-93ee-45ecf1ff11c5"),
                            Path = "people"
                        });
                });

            modelBuilder.Entity("devitemapi.Entity.DevMenuAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUser")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifyUser")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("DevMenuActions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ba6612d8-0f28-43c7-b4ec-5fb8e130b635"),
                            ActionId = new Guid("7b48a7f0-4077-4c1e-acd5-87ef0a8ace93"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(7655),
                            MenuId = new Guid("1ce75274-4033-4081-88d0-6ba7ef00fddd"),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(7659)
                        },
                        new
                        {
                            Id = new Guid("41dbae89-4b0c-4407-b18a-75d702639684"),
                            ActionId = new Guid("532e849c-b3d5-4d55-abfe-6e645ba2bae2"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(8725),
                            MenuId = new Guid("1ce75274-4033-4081-88d0-6ba7ef00fddd"),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(8730)
                        },
                        new
                        {
                            Id = new Guid("90f6e437-9fe3-4d5e-93b1-0d5e05d9d20d"),
                            ActionId = new Guid("7b48a7f0-4077-4c1e-acd5-87ef0a8ace93"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(8757),
                            MenuId = new Guid("19b93b25-5230-425b-b5c5-625b708915b5"),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(8758)
                        },
                        new
                        {
                            Id = new Guid("235deae7-b378-488e-bab9-4523a84d620b"),
                            ActionId = new Guid("532e849c-b3d5-4d55-abfe-6e645ba2bae2"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(8765),
                            MenuId = new Guid("19b93b25-5230-425b-b5c5-625b708915b5"),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(8766)
                        },
                        new
                        {
                            Id = new Guid("8df1d3ce-ed8a-4221-ae7d-12a886593cc5"),
                            ActionId = new Guid("7b48a7f0-4077-4c1e-acd5-87ef0a8ace93"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(8771),
                            MenuId = new Guid("daf50ad9-c46b-43de-aab2-ca4418785ba3"),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(8772)
                        },
                        new
                        {
                            Id = new Guid("997ef473-3aff-4db5-aec4-4feeefc3c8b6"),
                            ActionId = new Guid("7b48a7f0-4077-4c1e-acd5-87ef0a8ace93"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(8777),
                            MenuId = new Guid("a5e189c0-166a-4b37-93ee-45ecf1ff11c5"),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(8778)
                        });
                });

            modelBuilder.Entity("devitemapi.Entity.DevPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUser")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifyUser")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("DevPermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9372ae7-ebd4-4c4b-9e64-f55965d35e78"),
                            ActionId = new Guid("7b48a7f0-4077-4c1e-acd5-87ef0a8ace93"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 38, DateTimeKind.Local).AddTicks(9938),
                            MenuId = new Guid("19b93b25-5230-425b-b5c5-625b708915b5"),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 38, DateTimeKind.Local).AddTicks(9943),
                            RoleId = new Guid("557b25cc-463d-4116-9d7d-5003d6acbf6a")
                        },
                        new
                        {
                            Id = new Guid("028d9d91-2f5f-4503-803c-8296c4bae426"),
                            ActionId = new Guid("532e849c-b3d5-4d55-abfe-6e645ba2bae2"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(1656),
                            MenuId = new Guid("19b93b25-5230-425b-b5c5-625b708915b5"),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(1660),
                            RoleId = new Guid("557b25cc-463d-4116-9d7d-5003d6acbf6a")
                        },
                        new
                        {
                            Id = new Guid("e55c31ba-e4fc-4682-a4ad-b5eee06d2b3b"),
                            ActionId = new Guid("532e849c-b3d5-4d55-abfe-6e645ba2bae2"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(1698),
                            MenuId = new Guid("daf50ad9-c46b-43de-aab2-ca4418785ba3"),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(1699),
                            RoleId = new Guid("557b25cc-463d-4116-9d7d-5003d6acbf6a")
                        },
                        new
                        {
                            Id = new Guid("f93a453e-a93d-4314-803d-fe586c119bcd"),
                            ActionId = new Guid("255f3693-099d-432a-9a80-e377976f9c22"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(1706),
                            MenuId = new Guid("a5e189c0-166a-4b37-93ee-45ecf1ff11c5"),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(1707),
                            RoleId = new Guid("557b25cc-463d-4116-9d7d-5003d6acbf6a")
                        },
                        new
                        {
                            Id = new Guid("3e41c160-9781-4818-afb5-3d33455ab754"),
                            ActionId = new Guid("532e849c-b3d5-4d55-abfe-6e645ba2bae2"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(1714),
                            MenuId = new Guid("1ce75274-4033-4081-88d0-6ba7ef00fddd"),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 39, DateTimeKind.Local).AddTicks(1715),
                            RoleId = new Guid("557b25cc-463d-4116-9d7d-5003d6acbf6a")
                        });
                });

            modelBuilder.Entity("devitemapi.Entity.DevRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUser")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifyUser")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RoleCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RoleName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DevRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("557b25cc-463d-4116-9d7d-5003d6acbf6a"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 38, DateTimeKind.Local).AddTicks(6794),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 38, DateTimeKind.Local).AddTicks(6815),
                            RoleCode = "SuperAdmin",
                            RoleName = "超级管理员",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("78d6d23b-64c1-4d23-b766-a19276be3d1c"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 38, DateTimeKind.Local).AddTicks(6881),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 38, DateTimeKind.Local).AddTicks(6883),
                            RoleCode = "Admin",
                            RoleName = "管理员",
                            Status = 1
                        });
                });

            modelBuilder.Entity("devitemapi.Entity.DevUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Account")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUser")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("EMail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifyUser")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("DevUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc9e5615-17d5-4ca2-adf9-200f903e0a7d"),
                            Account = "Administrator",
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 36, DateTimeKind.Local).AddTicks(6995),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 36, DateTimeKind.Local).AddTicks(7569),
                            Pwd = "123456",
                            Status = 1,
                            UserName = "超级管理员"
                        });
                });

            modelBuilder.Entity("devitemapi.Entity.DevUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUser")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifyUser")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DevUserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9372ae7-ebd4-4c4b-9e64-f55965d35e78"),
                            CreateDate = new DateTime(2020, 10, 30, 10, 7, 36, 38, DateTimeKind.Local).AddTicks(7690),
                            ModifyDate = new DateTime(2020, 10, 30, 10, 7, 36, 38, DateTimeKind.Local).AddTicks(7695),
                            RoleId = new Guid("557b25cc-463d-4116-9d7d-5003d6acbf6a"),
                            UseId = new Guid("bc9e5615-17d5-4ca2-adf9-200f903e0a7d")
                        });
                });

            modelBuilder.Entity("devitemapi.Entity.Gold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConsignmentId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("GainTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("GoldAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SellerRoleName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ServerId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ServerName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ZoneId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ZoneName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Golds");
                });

            modelBuilder.Entity("devitemapi.Entity.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("devitemapi.Entity.nlogrec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Application")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Callsite")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Exception")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Levels")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LogContent")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Logger")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Message")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Operatingaddress")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Operatingtime")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Referrerurl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Requesturl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Userid")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Nlogrecs");
                });

            modelBuilder.Entity("devitemapi.Entity.DevMenuAction", b =>
                {
                    b.HasOne("devitemapi.Entity.DevMenu", "DevMenu")
                        .WithMany("DevMenuActions")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("devitemapi.Entity.DevPermission", b =>
                {
                    b.HasOne("devitemapi.Entity.DevRole", "DevRole")
                        .WithMany("DevPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("devitemapi.Entity.DevUserRole", b =>
                {
                    b.HasOne("devitemapi.Entity.DevUser", "User")
                        .WithMany("DevUserRoles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("devitemapi.Entity.Post", b =>
                {
                    b.HasOne("devitemapi.Entity.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
