// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using devitemapi.Entities;

namespace devitemapi.Migrations
{
    [DbContext(typeof(DevDbContext))]
    [Migration("20200812084706_create database")]
    partial class createdatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("devitemapi.Entities.DevAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ActionName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("DevActions");
                });

            modelBuilder.Entity("devitemapi.Entities.DevMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MenuName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("DevMenus");
                });

            modelBuilder.Entity("devitemapi.Entities.DevMenuAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("DevMenuActions");
                });

            modelBuilder.Entity("devitemapi.Entities.DevRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RoleName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DevRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("557b25cc-463d-4116-9d7d-5003d6acbf6a"),
                            CreateDate = new DateTime(2020, 8, 12, 16, 47, 6, 84, DateTimeKind.Local).AddTicks(4175),
                            ModifyDate = new DateTime(2020, 8, 12, 16, 47, 6, 84, DateTimeKind.Local).AddTicks(4217),
                            RoleName = "超级管理员",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("78d6d23b-64c1-4d23-b766-a19276be3d1c"),
                            CreateDate = new DateTime(2020, 8, 12, 16, 47, 6, 84, DateTimeKind.Local).AddTicks(4293),
                            ModifyDate = new DateTime(2020, 8, 12, 16, 47, 6, 84, DateTimeKind.Local).AddTicks(4295),
                            RoleName = "管理员",
                            Status = 1
                        });
                });

            modelBuilder.Entity("devitemapi.Entities.DevRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MemuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DevRolePermissions");
                });

            modelBuilder.Entity("devitemapi.Entities.DevUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Account")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EMail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("DevUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc9e5615-17d5-4ca2-adf9-200f903e0a7d"),
                            Account = "Administrator",
                            CreateDate = new DateTime(2020, 8, 12, 16, 47, 6, 81, DateTimeKind.Local).AddTicks(7769),
                            ModifyDate = new DateTime(2020, 8, 12, 16, 47, 6, 82, DateTimeKind.Local).AddTicks(8069),
                            Pwd = "123456",
                            Status = 1,
                            UserName = "超级管理员"
                        });
                });

            modelBuilder.Entity("devitemapi.Entities.DevUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Useid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DevUserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
