// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using devitemapi.Entity;

namespace devitemapi.Migrations
{
    [DbContext(typeof(DevDbContext))]
    [Migration("20200907033804_Add menu role action")]
    partial class Addmenuroleaction
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("devitemapi.Entity.DevAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ActionName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("DevActions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b48a7f0-4077-4c1e-acd5-87ef0a8ace93"),
                            ActionCode = "Query",
                            ActionName = "查询",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("532e849c-b3d5-4d55-abfe-6e645ba2bae2"),
                            ActionCode = "Add",
                            ActionName = "增加",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("39579c2f-7f92-4cd0-bf51-76a7a01c8e16"),
                            ActionCode = "Delete",
                            ActionName = "删除",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("devitemapi.Entity.DevMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MenuCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MenuName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("DevMenus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("19b93b25-5230-425b-b5c5-625b708915b5"),
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "/item.ico",
                            MenuCode = "Index",
                            MenuName = "首页",
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 0,
                            Url = "localhost:8080"
                        });
                });

            modelBuilder.Entity("devitemapi.Entity.DevMenuAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("DevMenuActions");
                });

            modelBuilder.Entity("devitemapi.Entity.DevPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MemuId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("DevPermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9372ae7-ebd4-4c4b-9e64-f55965d35e78"),
                            ActionId = new Guid("7b48a7f0-4077-4c1e-acd5-87ef0a8ace93"),
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemuId = new Guid("19b93b25-5230-425b-b5c5-625b708915b5"),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("557b25cc-463d-4116-9d7d-5003d6acbf6a")
                        });
                });

            modelBuilder.Entity("devitemapi.Entity.DevRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RoleCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RoleName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DevRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("557b25cc-463d-4116-9d7d-5003d6acbf6a"),
                            CreateDate = new DateTime(2020, 9, 7, 11, 38, 3, 445, DateTimeKind.Local).AddTicks(5573),
                            ModifyDate = new DateTime(2020, 9, 7, 11, 38, 3, 445, DateTimeKind.Local).AddTicks(5602),
                            RoleCode = "SuperAdmin",
                            RoleName = "超级管理员",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("78d6d23b-64c1-4d23-b766-a19276be3d1c"),
                            CreateDate = new DateTime(2020, 9, 7, 11, 38, 3, 445, DateTimeKind.Local).AddTicks(5671),
                            ModifyDate = new DateTime(2020, 9, 7, 11, 38, 3, 445, DateTimeKind.Local).AddTicks(5672),
                            RoleCode = "Admin",
                            RoleName = "管理员",
                            Status = 1
                        });
                });

            modelBuilder.Entity("devitemapi.Entity.DevUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Account")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EMail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("DevUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc9e5615-17d5-4ca2-adf9-200f903e0a7d"),
                            Account = "Administrator",
                            CreateDate = new DateTime(2020, 9, 7, 11, 38, 3, 443, DateTimeKind.Local).AddTicks(8497),
                            ModifyDate = new DateTime(2020, 9, 7, 11, 38, 3, 443, DateTimeKind.Local).AddTicks(9046),
                            Pwd = "123456",
                            Status = 1,
                            UserName = "超级管理员"
                        });
                });

            modelBuilder.Entity("devitemapi.Entity.DevUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Useid")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("DevUserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9372ae7-ebd4-4c4b-9e64-f55965d35e78"),
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("557b25cc-463d-4116-9d7d-5003d6acbf6a"),
                            Useid = new Guid("bc9e5615-17d5-4ca2-adf9-200f903e0a7d")
                        });
                });

            modelBuilder.Entity("devitemapi.Entity.nlogrec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Application")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Callsite")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Exception")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Levels")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LogContent")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Logger")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Message")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Operatingaddress")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Operatingtime")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Referrerurl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Requesturl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Userid")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Nlogrecs");
                });
#pragma warning restore 612, 618
        }
    }
}
